# Generated by Django 5.1.1 on 2024-10-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='product_images/default.jpg', null=True, upload_to='product_images'),
        ),
    ]
